#! /bin/sh
### BEGIN INIT INFO
# Provides: libipho
# Required-Start: $remote_fs $syslog $networking
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Photobooth
# Description: This file starts and stops the Libipho photobooth
#
### END INIT INFO

[ -f /etc/profile.d/set-libipho-base ] && . /etc/profile.d/set-libipho-base

if [ -z "$LIBIPHO_BASE" ] ;  then
  echo "LIBIPHO_BASE is not set, please set it in /etc/profile.d/set-libipho-base" >&2
  exit 1
fi

DAEMON=$LIBIPHO_BASE/capture.sh
NAME="libipho"
DESC="libipho main process"
PIDFILE="/var/run/$NAME.pid"

STARTOPTS="--start --background --pidfile=$PIDFILE --make-pidfile --chuid libipho:libipho"
STOPOPTS="--stop --pidfile=$PIDFILE"

case "$1" in
  start)
    echo -n "Starting $DESC: "
    start-stop-daemon $STARTOPTS -x "$DAEMON"
    echo "$NAME."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    start-stop-daemon $STOPOPTS
    rm -f $PIDFILE
    echo "$NAME."
    ;;
  restart|force-reload)
    echo -n "Restarting $DESC: "
    start-stop-daemon $STOPOPTS
    sleep 1
    start-stop-daemon $STARTOPTS -x "$DAEMON"
    echo "$NAME."
    ;;
 *)
   echo "Usage: $NAME {start|stop|restart|force-reload}" >&2
   exit 1
   ;;
esac

