#! /bin/sh
### BEGIN INIT INFO
# Provides: libipho-gpio-button
# Required-Start: $remote_fs $syslog $networking
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Photobooth GPIO buttons
# Description: This file starts and stops the gpio
#              service that listens to the libipho buttons.
#
### END INIT INFO

[ -f /etc/profile.d/set-libipho-base ] && . /etc/profile.d/set-libipho-base

if [ -z "$LIBIPHO_BASE" ] ;  then
  echo "LIBIPHO_BASE is not set, please set it in /etc/profile.d/set-libipho-base" >&2
  exit 1
fi


DAEMON=$LIBIPHO_BASE/gpio/gpio_button_listener.sh
NAME="libipho-gpio-button"
DESC="process that reacts on the gpio buttons"
PIDFILE="/var/run/$NAME.pid"

STARTOPTS="--start --background --pidfile=$PIDFILE --make-pidfile --chuid libipho:libipho"
STOPOPTS="--stop --pidfile=$PIDFILE"

case "$1" in
  start)
    echo -n "Starting $DESC: "
    $LIBIPHO_BASE/gpio/gpio_button_enable.sh
    start-stop-daemon $STARTOPTS -x "$DAEMON"
    echo "$NAME."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    start-stop-daemon $STOPOPTS
    $LIBIPHO_BASE/gpio/gpio_button_disable.sh
    rm -f $PIDFILE
    echo "$NAME."
    ;;
  restart|force-reload)
    echo -n "Restarting $DESC: "
    $LIBIPHO_BASE/gpio/gpio_button_disable.sh
    start-stop-daemon $STOPOPTS
    sleep 1
    $LIBIPHO_BASE/gpio/gpio_button_enable.sh
    start-stop-daemon $STARTOPTS -x "$DAEMON"
    echo "$NAME."
    ;;
 *)
   echo "Usage: $NAME {start|stop|restart|force-reload}" >&2
   exit 1
   ;;
esac

