#! /bin/sh
### BEGIN INIT INFO
# Provides: libipho-gpio-button
# Required-Start: $remote_fs $syslog $networking
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Photobooth GPIO buttons
# Description: This file starts and stops the gpio
#              service that listens to the libipho buttons.
#
### END INIT INFO

[ -f /etc/profile.d/set-libipho-base ] && . /etc/profile.d/set-libipho-base

if [ -z "$LIBIPHO_BASE" ] || [ -z "$LIBIPHO_WWW" ];  then
  echo "LIBIPHO_BASE or LIBIPHO_WWW is not set, please set it in /etc/profile.d/set-libipho-base" >&2
  exit 1
fi


DAEMON=$LIBIPHO_BASE/gpio/gpio_button_listener.sh
NAME="libipho-gpio-button"
DESC="process that reacts on the gpio buttons"
PIDFILE="/var/run/$NAME.pid"

STARTOPTS="--start --background --pidfile=$PIDFILE --make-pidfile --chuid libipho:libipho"
STOPOPTS="--stop --pidfile=$PIDFILE"

case "$1" in
  start)
    # start-stop-daemon fails to recognize an already running instance
    # of the process and therefore does not prevent us from starting
    # the process twice. Therefore, we explicitly check for the
    # existence of a process with the given PID and abort if
    # a corresponding process has been found.
    start-stop-daemon -p $PIDFILE -t -K 2>&1 > /dev/null
    ISDEAD=$?
    if [ "$ISDEAD" = "0" ]; then
      echo "A process the the PID specified in $PIDFILE is already running."
      exit 0
    fi
    echo -n "Starting $DESC: "
    $LIBIPHO_BASE/gpio/gpio_button_enable.sh
    start-stop-daemon $STARTOPTS -x "$DAEMON"
    echo "$NAME."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    start-stop-daemon $STOPOPTS
    $LIBIPHO_BASE/gpio/gpio_button_disable.sh
    rm -f $PIDFILE
    echo "$NAME."
    ;;
  restart|force-reload)
    echo -n "Restarting $DESC: "
    $LIBIPHO_BASE/gpio/gpio_button_disable.sh
    start-stop-daemon $STOPOPTS
    sleep 1
    $LIBIPHO_BASE/gpio/gpio_button_enable.sh
    start-stop-daemon $STARTOPTS -x "$DAEMON"
    echo "$NAME."
    ;;
 *)
   echo "Usage: $NAME {start|stop|restart|force-reload}" >&2
   exit 1
   ;;
esac

