#!/bin/bash
echo Replace $1 with $2.

read -p "Are you sure? " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi
echo " Replacing ..."
sed -i "s/$1/$2/g" *.sh
sed -i "s/$1/$2/g" gallery/*.sh
sed -i "s/$1/$2/g" gpio/*.sh
sed -i "s/$1/$2/g" screen/*.sh
sed -i "s/$1/$2/g" tools/*.sh
